### PR TITLE
simplify readstdin

### PR DESCRIPTION
**Pull request by N-R-K**
Didn't test too much, but I think this should be fine. Uses similar logic to nsxiv's `xgetline()`.

### CODE REVIEW

**Comment by explosion-mental** [comment]
I would like to have main very clean so, can you try to merge everything into `readstdin`?
I've come up with
```c
void
readstdin(void)
{
	char *line = NULL;
	size_t n = 0;
	ssize_t len;

	while ((len = getline(&line, &n, stdin)) > 0) {
		if (line[len-1] == '\n') /* stop reading at new line */
			line[len-1] = '\0';
		if (!strcmp(line, "")) { /* TODO if the line is empty / null */
			continue;
			//free(line);
		}
		check_file(line);
	}
}
```
but looks like it only loads the last entry. 
_Ignore the strcmp block, wanted to ignore accidental presses of the `return` key and ommit warnings when the line is "" ._

**Comment by N-R-K** [comment]
> but looks like it only loads the last entry

Probably because `check_file` stores the pointer directly while in sxiv the string is duplicated. Duplicating the string before passing it to check_file would probably work. I'll try it out.

**Comment by N-R-K** [comment]
Hmm, probably don't need the string duplicate. I'll try setting line to NULL instead.

**Comment by N-R-K** [comment]
Yeah, this seems to work as well. If `line` is NULL getline will allocate space for it.

**Comment by explosion-mental** [comment]
Very nice! thank you @N-R-K. 

Just now I'm working on the scalemodes branch, I'm giving a try a dwm idea, could you give me your thoughts of a quick look?

**Comment by N-R-K** [comment]
> Just now I'm working on the scalemodes branch, I'm giving a try a dwm idea, could you give me your thoughts of a quick look?

What's the reason for it, So that people can add their custom zoom function? Having a custom layout (in dwm) is a pretty common use-case, I don't see wanting a custom zoom function being common enough of a use-case tbh.

**Comment by explosion-mental** [comment]
> What's the reason for it, So that people can add their custom zoom function? Having a custom layout (in dwm) is a pretty common use-case, I don't see wanting a custom zoom function being common enough of a use-case tbh.

good point, there are only `down - fit - width - height - fill` scale modes that I know of. Maybe 'upgrading' this idea into _'thumbnail mode layouts'_ would be more 'useful' : e.g. `book mode` only show two images on the windows or `tiling mode` which would show the same image repeadtedly, etc.

Now that I say these ideas out loud, I think instead of having a fixed 'thumbnail mode' I now consider more 'extensible' to have an 'custom mode' or 'alternative mode' or whatever..

**Comment by N-R-K** [comment]
@explosion-mental Yes, having custom functions for layout makes sense. People can extend it to dual page or other mode as they like.

**Pull request merged**
