### PR TITLE
fix: memory leak, free all filenames

### PR DESCRIPTION
**Pull request by N-R-K**
Additionally, I would suggest allocating a large chunk at first and then reallocating x2 when filled similar to sxiv instead of reallocating on each addition.

### CODE REVIEW

**Comment by N-R-K** [comment]
Hmm, wait. This only works when opening a directory.

**Comment by N-R-K** [comment]
Or when using stdin, `readstdin()` seems to be doing allocation as well.

**Comment by explosion-mental** [comment]
I didn't bother with `readstdin()`, so it's the same function sxiv has but without the `ignoring null strings` or something similar, so yeah there is probably a much better way of reading stdin. I looked a bit on `dmenu` but still don't know how to simplify this.

**Comment by explosion-mental** [comment]
> Additionally, I would suggest allocating a large chunk at first and then reallocating x2 when filled similar to sxiv instead of reallocating on each addition.

So something like `filenames = malloc(size * sizeof (char *))` where size is just an arbitrary number like '512'?
I'm thinking about not storing the filename anymore, only when reading the directory, and instead use imlib2 function to get the filename (just like it does to get the width and height) which is `imlib_get_image_filename()` or something like that. This means to only care about the `filecnt` and `fileidx`.

Still thinking tho.

**Comment by N-R-K** [comment]
@explosion-mental on second thought, I think it's okay to not free the filenames since they live for the entire duration of the app's life. So it's not exactly a memory leak, the OS will reclaim the memory on exit.

From a quick glance, I don't see sxiv freeing the filenames in it's cleanup function either.

**Comment by N-R-K** [comment]
> I didn't bother with `readstdin()`, so it's the same function sxiv has but without the `ignoring null strings` or something similar, so yeah there is probably a much better way of reading stdin. I looked a bit on `dmenu` but still don't know how to simplify this.

I have an idea for it, see https://github.com/explosion-mental/mage/pull/4

**Comment by N-R-K** [comment]
Closing this, reason: https://github.com/explosion-mental/mage/pull/3#issuecomment-974729152

**Pull request closed without merging**
